### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/data/NYT/ner2idx.json'

### ISSUE THREAD

**Issue by manzoorali29** [Coopercoppers/PFN#13]
Hi,
I have tried Evaluation on Pre-trained Model for NYT and WEBNLG, but the system shows an error about the ner2idx.json file. The files are there but have no content. I have also tried to generate it using dataloder.py, but it shows the following error ModuleNotFoundError: No module named 'utils'. 
Can you please fix them or suggest to me an alternate solution? 
Thanks for sharing such a nice repo.

**Comment by Coopercoppers** [comment]
Maybe it's because the directory wasn't set up properly? like why would you have directory entry like data/data? it should be data/NYT instead.
