### ISSUE TITLE
Question about entity extraction of out-of-triples

### ISSUE THREAD

**Issue by AndDoIt** [Coopercoppers/PFN#15]
Thanks for your talented and excellent work!  
I wondered whether there are some considerable ways to make up for relation information gain that out-of-triples entity missed?

**Comment by Coopercoppers** [comment]
Maybe split the task of entity recognition into two subtasks (in-triple and out-of-triple entity recognition). You can produce separate features for the tasks, and/or expand the label settings of entity recognition to more fine-grained types, like out-of-triple person and in-triple person.
