### ISSUE TITLE
chinese custom dataset  

### ISSUE THREAD

**Issue by xxllp** [Coopercoppers/PFN#16]
中文的数据格式需要转换成哪张数据集的 格式才可以

**Comment by Coopercoppers** [comment]
随便哪个都行，所有的数据集经过preprocess函数之后都会转换成统一格式，你可以先转换成任意已有数据集的格式，或者是自定义preprocess函数，直接转换成类似ace_preprocess的输出形式

另外中文数据集用pfn-nested，尽量不要用原模型

**Comment by guanxichouqu** [comment]
> 中文的数据格式需要转换成哪张数据集的 格式才可以

你好 请问一下 我最近也想用该模型在中文数据集上测试测试效果  可以向你请问一下相关经验吗
