### ISSUE TITLE
evaluate the model with customized input

### ISSUE THREAD

**Issue by DK158** [Coopercoppers/PFN#17]
I appreciate the work you shared, but I'm having some problems

I have many samples to predict, what should I do with them？
`python inference.py `
`--model_file ${the path of your saved model} `
`--sent ${sentence you want to evaluate, str type restricted}`
This approach seems to load the model once to process only one sample, which is very slow. Is there any way to process all samples after loading the model once? Do you have any suggestions?

Thanks.

**Comment by Coopercoppers** [comment]
You can make some changes to the inference file. Like you can batchify your samples and feed them to the model, and then you add another for loop to process each samples to get the triple results.

**Comment by DK158** [comment]
> 

Thank you for your answer, I got it.
