### ISSUE TITLE
请问消融实验的编码模式encoding scheme应该怎么设置呀

### ISSUE THREAD

**Issue by aaa1999** [Coopercoppers/PFN#18]
如题，想知道怎么改代码和数据完成消融实验的encoding scheme呀，对比sequential encoding和parellel encoding两种方式。谢谢

**Comment by Coopercoppers** [comment]
把编码器换成两个lstm就可以了。
sequential的话，输入x到第一个lstm得到输出作为ner特征，然后将ner特征输入到第二个lstm得到re特征。
Parallel就是两个lstm输入x分别得到ner和re的特征。

**Comment by aaa1999** [comment]
好的，谢谢。
