### ISSUE TITLE
Nest下的处理

### ISSUE THREAD

**Issue by Hou-jing** [Coopercoppers/PFN#19]
您好，请问，您们是如何在以表表示的方式下，处理嵌套实体的关系识别的呢？方便将大致思路分享下吗？（如下，是您们在github中的实例）
![image](https://user-images.githubusercontent.com/75936962/165870031-d2d53d63-8fd9-4769-9f36-b7177705bcac.png)

**Comment by Coopercoppers** [comment]
可以参考下nested文件夹metrics.py里的get_trip函数，应该能找到你要的答案

**Comment by Hou-jing** [comment]
谢谢，我看到了，您们在relation的预测中同时考虑头尾的匹配~
