### ISSUE TITLE
SEMEVAL dataset

### ISSUE THREAD

**Issue by arian1995** [Coopercoppers/PFN#20]
I have a dataset that is a translated version of SEMEVAL. I tried to change your code to evaluate your model on my dataset but I didn't get good results. so I want to know why you didn't report your model's performance on SEMEVAL? you didn't try at all or for some reason it didn't work?

**Comment by Coopercoppers** [comment]
For all I know, SemEval is a dataset used for RELATION EXTRACTION, not JOINT ENTITY AND RELATION EXTRACTION, it's similar to the likes of Tacred dataset. Of course you can modify your task to include entity extraction. But when you try out some new dataset, if you don't get good result, make sure the data preprocessing is correct and hyper-parameters are tuned properly.

best wishes
