### ISSUE TITLE
为什么PFN-nested model在关系训练时候可以利用实体tail信息呢？

### ISSUE THREAD

**Issue by jingsongs** [Coopercoppers/PFN#21]
您好：
       膜拜您的设计和实现！！！有一个小问题想请教一下：
       您的介绍中提到：PFN-nested is an enhanced version of PFN. It is better in leveraging entity tail information and capable of handling nested triple prediction. 在PFN-nested网络结构中（PFN.py），有这样的代码：
          re_head_score = self.re_head(h_re, h_share, mask)      
          re_tail_score = self.re_tail(h_share, h_re, mask)  
       分别是利用实体head和tail的信息进行关系抽取对吧？在这里self.re_head和self.re_tail都是re_unit结构，仅仅将这里的h_share, h_re换一下位置，是如何利用的tail信息的呢？self.re_tail(h_share, h_re, mask)利用的是h_share中的信息计算的r1和r2，如何体现的tail信息呢？

**Comment by Coopercoppers** [comment]
谢谢关注，实体tail信息来源于label打标给他的一个监督信息，这里head和tail分别用h_re和h_share作为主要的特征，可以实现这两部分信息的区分，这和ner，re用不同特征来计算是一个道理。具体理由可以参考nested文件夹下readme的justification。

**Comment by jingsongs** [comment]
明白了，谢谢！！
