### ISSUE TITLE
关于实体抽取和关系抽取F1分数问题

### ISSUE THREAD

**Issue by WangYao-GoGoGo** [Coopercoppers/PFN#25]
作者你好！
       您论文中的实体抽取和关系抽取的F1的分数取的是联合分数还是单项最高分数？您实验过程中有存在单项最高的分数可能不在同一个epoch里的情况吗？谢谢！

**Comment by Coopercoppers** [comment]
联合分数；可能存在单项分数不是最高的情况，页面里有提供模型训练和测试时每个epoch的分数和loss，需要的话可以下载下来看一下

**Comment by WangYao-GoGoGo** [comment]
哦，好的好的，谢谢您的回答
