### ISSUE TITLE
关于OOT（Out-of-triple）数据集问题

### ISSUE THREAD

**Issue by WangYao-GoGoGo** [Coopercoppers/PFN#26]
请教一下，您论文中关于测试OOT实体时，训练集，验证集也有分割成OOT实体的数据集吗？然后模型是基于OOT的训练集重新训练一遍，测试OOT实体，还是拿原训练集（包含oot数据和in-triple数据）训练好的模型，来预测oot的测试集？

**Comment by Coopercoppers** [comment]
不是，没有改训练集，只是把测试集的数据切成了oot和it。另外麻烦不要发邮件给非一作的其他人谢谢，发给我就行了。

**Comment by WangYao-GoGoGo** [comment]
好的好的，收到，谢谢您的回答，因为正在赶论文所以有点着急，不好意思
