### ISSUE TITLE
why use albert-xxlarge instead of bert-base when training on some datasets?

### ISSUE THREAD

**Issue by Kobayashi-Wang** [Coopercoppers/PFN#7]
I run the code using bert-base on the dataset Conll04, and got F1-scores approximately 66. I find the f1 is much lower than using albert-large. I wonder whether the comparison between this model using albert-large and the previous work using bert-base is really reasonable?

**Comment by Coopercoppers** [comment]
Table-sequence uses Albert-xxlarge, and we want to make the experiment setting the same as the previous sota.
Also, as I mention, model is delicate in this dataset, you need to carefully tune the hyper parameters even if the only change you make is the embedding.  
3-4 point difference between Bert and Albert should be reasonable, I suggest that you tune the lr, batch size and clip

**Comment by Kobayashi-Wang** [comment]
I get it, thank you very much for your reply！
