### ISSUE TITLE
有一个报错问题，不知道是环境不对还是，

### ISSUE THREAD

**Issue by aaa1999** [Coopercoppers/PFN#9]
您好，我应该用的是30系列的显卡，然后按照这个requirements的环境要求安装了相关的环境，然而，当我运行
python main.py \
--data CONLL04 \
--do_train \
--do_eval \
--embed_mode albert \
--batch_size 10 \
--lr 0.00002 \
--output_file conll04 \
--eval_metric micro \
--clip 1.0 \
--epoch 200
这个命令的时候，给我报错如下:

11/22/2021 14:59:58 - INFO - __main__ - ['main.py', '--data', 'CONLL04', '--do_train', '--do_eval', '--embed_mode', 'albert', '--batch_size', '10', '--lr', '0.00002', '--output_file', 'conll04', '--eval_metric', 'micro', '--clip', '1.0', '--epoch', '200']
11/22/2021 14:59:58 - INFO - __main__ - Namespace(batch_size=10, clip=1.0, data='CONLL04', do_eval=True, do_train=True, dropconnect=0.1, dropout=0.1, embed_mode='albert', epoch=200, eval_batch_size=10, eval_metric='micro', hidden_size=300, linear_warmup_rate=0.0, lr=2e-05, max_seq_len=128, output_file='conll04', seed=0, steps=50, weight_decay=0)
11/22/2021 15:00:19 - INFO - __main__ - ------Training------
Some weights of the model checkpoint at albert-xxlarge-v1 were not used when initializing AlbertModel: ['predictions.decoder.bias', 'predictions.bias', 'predictions.LayerNorm.weight', 'predictions.dense.bias', 'predictions.decoder.weight', 'predictions.LayerNorm.bias', 'predictions.dense.weight']
- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/ps/anaconda3/envs/lwc/lib/python3.7/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/home/ps/anaconda3/envs/lwc/lib/python3.7/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
  0%|                                                                                                                      | 0/93 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    ner_pred, re_pred = model(text, mask)
  File "/home/ps/anaconda3/envs/lwc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ps/lwc/PFN/model/pfn.py", line 260, in forward
    x = self.bert(**x)[0]
  File "/home/ps/anaconda3/envs/lwc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ps/anaconda3/envs/lwc/lib/python3.7/site-packages/transformers/models/albert/modeling_albert.py", line 715, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=self.dtype)  # fp16 compatibility
**RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

不是很明白这个错误。pytorch的社区解释说，是pytorch的版本不对而引起的，但是没有找到合理的解决方案，请您帮助，谢谢。

**Comment by Coopercoppers** [comment]
看你这好像用的3080, 换个torch版本试试？1.8或者1.7那种。另外检查一下你的cuda版本

**Comment by aaa1999** [comment]
> 

好，我再看看。

**Comment by aaa1999** [comment]
> 看你这好像用的3080, 换个torch版本试试？1.8或者1.7那种。另外检查一下你的cuda版本

我这torch 的版本是 
 >>> torch.__version__
'1.9.0+cu102'
是高了吗？

**Comment by Coopercoppers** [comment]
这是cuda以及设备和pytorch版本不兼容的问题，网上应该有不少解决方案，可以去看看，这边我可能也帮不上忙。

**Comment by aaa1999** [comment]
> 

好的，谢谢，我自己先弄一下。
